site_name: Star Control
site_url: https://focustense.github.io/StardewControllers
repo_name: focustense/StardewControllers
repo_url: https://github.com/focustense/StardewControllers
theme:
  name: material
  custom_dir: docs_override
  features:
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: images/logo-mini-beveled.png
extra_css:
  - stylesheets/styles.css
  - stylesheets/github-permalink-style.css
plugins:
  - awesome-pages
  - search
  - social
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs_override/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/focustense
    - icon: simple/nexusmods
      link: https://next.nexusmods.com/profile/focustense/mods?gameId=1303